---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Platform running
      ansible.builtin.debug:
        var: ansible_lsb
    - name: Install node
      ansible.builtin.include_role:
        name: "install_node"
      vars:
        use_systemd: false
