---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Check that crictl exists
      ansible.builtin.command: "crictl -v"
      register: command_output
      changed_when: false
      failed_when: command_output.rc != 0

    - name: Check that containerd exists
      ansible.builtin.command: "containerd -v"
      register: command_output
      changed_when: false
      failed_when: command_output.rc != 0

    - name: Check that kubectl exists
      ansible.builtin.command: "kubectl version --client"
      register: command_output
      changed_when: false
      failed_when: command_output.rc != 0

    - name: Check that Kubelet exists
      ansible.builtin.command: "kubelet --version"
      register: command_output
      changed_when: false
      failed_when: command_output.rc != 0

    - name: Check that kube-proxy exists
      ansible.builtin.command: "kube-proxy --version"
      register: command_output
      changed_when: false
      failed_when: command_output.rc != 0
