- name: Setup Linux
  become: yes
  hosts: knode1
#  hosts: localhost
#  connection: local
  gather_facts: no
  vars:
    package_list:
          - curl
          - socat  
          - tar
          - zipinfo
          - gzip 
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install necessary packages
      apt:
        pkg: "{{package_list}}"
        state: latest