- name: Install CNI plugin
  become: yes
  hosts: knode1
#  hosts: localhost
#  connection: local
  gather_facts: no
  vars:
    cni_version: "v1.1.1"
    cni_bin_dir: /opt/cni/bin
    cni_tarball: /tmp/cni-plugin.tgz
    architecture: "amd64"
  tasks:
    - name: Create CNI directory
      file:
        path: "{{cni_bin_dir}}"
        state: directory
        mode: 0755  
    - name: Download CNI binary
      get_url:
        url: https://github.com/containernetworking/plugins/releases/download/{{cni_version}}/cni-plugins-linux-{{architecture}}-{{cni_version}}.tgz
        dest: "{{cni_tarball}}"
        mode: 0755  
    - name: Extract CNI release content
      unarchive:
        src: "{{cni_tarball}}"
        dest: "{{cni_bin_dir}}" 
        remote_src: yes   