- name: Install Container Runtime Interface CLI
  become: yes
  hosts: knode1
#  hosts: localhost
#  connection: local
  gather_facts: no
  vars:
    cri_version: "v1.24.2"
    cri_bin_dir: /usr/local/bin
    cri_tarball: /tmp/cri.tgz
    architecture: "amd64"
  tasks:
    - name: Download CRI binary
      get_url:
        url: https://github.com/kubernetes-sigs/cri-tools/releases/download/{{cri_version}}/crictl-{{cri_version}}-linux-{{architecture}}.tar.gz
        dest: "{{cri_tarball}}"
        mode: 0755  
    - name: Extract CRI binary
      unarchive:
        src: "{{cri_tarball}}"
        dest: "{{cri_bin_dir}}" 
        mode: 0555
        remote_src: yes