- name: Install node Kubernetes binaries
  become: yes
  hosts: knode1
#  hosts: localhost
#  connection: local
  gather_facts: no
  vars:
    architecture: "amd64"
    binaries:
      - kubelet
      - kube-proxy
  tasks:
    - name: Find latest stable Kubernetes version
      uri:
        url: https://dl.k8s.io/release/stable.txt
        return_content: yes
      register: kubernetes_version
    - name:
      get_url:
        url: https://dl.k8s.io/release/{{kubernetes_version.content}}/bin/linux/{{architecture}}/{{item}}
        dest: /usr/local/bin/{{item}}
        mode: 0555
      loop: "{{binaries}}"