---
# Kubernetes specific
# kubernetes_release_url: "https://dl.k8s.io/release/stable.txt"
# Only runs if set to fetch latest version.
- name: Find latest stable Kubernetes version
  ansible.builtin.uri:
    url: "{{ kubernetes_release_url }}"
    return_content: true
  register: kubernetes_version_fetched
  when: kubernetes_version == "latest"

- name: Set Kubernetes version
  ansible.builtin.set_fact:
    kubernetes_version: "{{ kubernetes_version_fetched.content }}"
  when: kubernetes_version == "latest"
