---
- name: Test simple roles/tasks locally
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  vars:
    nodes_worker:
      node01:
        ip: 10.101.101.1
        fqdn: node01.juannfox
      node02:
        ip: 10.101.101.2
        fqdn: node02.juannfox
    certificates_path: /etc/pki
    ca_key: "{{ certificates_path }}/ca.key"
    ca_csr: "{{ certificates_path }}/ca.csr"
    ca_crt: "{{ certificates_path }}/ca.crt"
    force_overwrite: false
  tasks:
    - name: Include task
      ansible.builtin.include_tasks: roles/create_certificates/tasks/main.yml



