---
- name: Test simple roles/tasks locally
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  vars:
    nodes_worker:
      node01:
        ip: 10.101.101.1
        fqdn: node01.juannfox
      node02:
        ip: 10.101.101.2
        fqdn: node02.juannfox
    nodes_master:
      master01:
        ip: 10.200.201.1
        fqdn: master01.juannfox
      master02:
        ip: 10.200.202.2
        fqdn: master02.juannfox        
    certificates_path: "/tmp/certificates"
    certificates_path_permissions: "0777"
    ca_key: "{{ certificates_path }}/ca.key"
    ca_csr: "{{ certificates_path }}/ca.csr"
    ca_crt: "{{ certificates_path }}/ca.crt"
    force_overwrite: false
    kubeconfig_path: /tmp/kubeconfig
    kubeconfig_path_permissions: "0777"
    kubeconfig_file_permissions: "0666"
    cluster_url: "https://localhost:6443"
    cluster_name: "k8s-hard-way"
    component_tls_subjects:
      admin:
        common_name: admin
        organization_name: system:masters 
      kube-proxy:
        common_name: system:kube-proxy
        organization_name: system:node-proxier
      kube-controller-manager:
        common_name: system:kube-controller-manager
        organization_name: system:kube-controller-manager
      kube-scheduler:
        common_name: system:kube-scheduler
        organization_name: system:kube-scheduler
    kube_apiserver_tls_subject:
      name: kube-apiserver
      common_name: kubernetes
      organization_name: Kubernetes
      san: "DNS:kubernetes.default;DNS:kubernetes.default.svc;DNS:kubernetes.default.svc.cluster;DNS:kubernetes.svc.cluster.local"
      subject_alternative_name:
        - "DNS:kubernetes.default"
        - "DNS:kubernetes.default.svc"
        - "DNS:kubernetes.default.svc.cluster"
        - "DNS:kubernetes.svc.cluster.local"
    kubelet_tls_subject:
      name: "kubelet"
      common_name: "system:node"
      organization_name: "system:nodes"  

  tasks:
    - name: Include task
      ansible.builtin.include_tasks: roles/create_certificates/tasks/main.yml