---
- name: Create CNI directory
  ansible.builtin.file:
    path: "{{ cni_bin_dir }}"
    state: directory
    mode: "0755"

- name: Download CNI binary
  ansible.builtin.get_url:
    url: "{{ cni_releases_url }}"
    dest: "{{ cni_tarball }}"
    mode: "0655"

- name: Extract and install CNI release content
  ansible.builtin.unarchive:
    src: "{{ cni_tarball }}"
    dest: "{{ cni_bin_dir }}"
    mode: "0755"
    remote_src: true
