---
- name: OS verification
  ansible.builtin.assert:
    that:
      - ansible_distribution == "Ubuntu"
      - ansible_distribution_version == "20.04"
      - ansible_architecture == "{{ architecture }}"

- name: Install necessary OS packages
  ansible.builtin.apt:
    pkg: "{{ apt_prerequisites }}"
    state: present
    update_cache: true

- name: Install Containerd (runtime)
  ansible.builtin.include_tasks: containerd/main.yml

- name: Install Kubernetes binaries
  ansible.builtin.include_tasks: kubernetes/main.yml
