---
#### KUBERNETES ####
# Kubernetes version to use.
# For more details check: https://kubernetes.io/releases/
kubernetes_version: "latest"
# K8s node binaries to install
kubernetes_binaries_node:
  - kubelet
  - kube-proxy
# Path for Kubernetes binaries
kubernetes_binaries_path: /usr/local/bin/
# File permissions for Kubernetes binaries. Must be
# an integer-type valid DAC code (type-user-group-other);
# defaults to Read+Execution for all.
kubernetes_binaries_dac_code: "0555"
kubernetes_binary_releases_url: >-
  https://dl.k8s.io/release/{{ kubernetes_version }}
  /bin/linux/{{ architecture }}

#### CONTAINERD RUNTIME ####
# Check for compatibility with K8s and CRI versions.
containerd_version: "1.6.6"
# Containerd install dir
containerd_dir: /usr/local
# Containerd download tarball path
containerd_tarball: /tmp/containerd.tgz
# Containerd Systemd unit file destination path
containerd_systemd_unit: /etc/systemd/system/containerd.service
# Containerd Systemd unit
containerd_daemon: containerd
# Whether to use Systemd for containerd
containerd_use_systemd: true
# Releases URL for Containerd
containerd_release_url: >-
  https://github.com/containerd/containerd/releases/download/
  v{{ containerd_version }}/containerd-{{ containerd_version }}
  -linux-{{ architecture }}.tar.gz

#### CRI ####
# CRI path
cri_bin_dir: /usr/local/bin
# CRI downlaod tarball path
cri_tarball: /tmp/cri.tgz
# Container Runtime Interface (CRI) specific. Check for compatibility
# with K8s and Containerd versions.
cri_version: "v1.24.2"
# CRI releases URL
cri_releases_url: >-
  https://github.com/kubernetes-sigs/cri-tools/releases/download/
  {{ cri_version }}/crictl-{{ cri_version }}-linux-{{ architecture }}.tar.gz

#### CNI PLUGIN ####
cni_version: "v1.1.1"
cni_bin_dir: /opt/cni/bin
cni_tarball: /tmp/cni-plugin.tgz
cni_url_1: "https://github.com/containernetworking/plugins/releases/download/"
cni_url_2: "{{ cni_version }}/cni-plugins-linux"
cni_url_3: "-{{ architecture }}-{{ cni_version }}.tgz"
cni_url: "{{ cni_url_1 }}{{ cni_url_2 }}{{ cni_url_3 }}"

#### OS SETTINGS ####
# CPU arch
architecture: "amd64"
# Default OS packages to install
apt_prerequisites:
  - curl
  - socat
  - tar
  - gzip
