---
# defaults

certificates_path: /etc/pki
ca_key: "{{ certificates_path }}/ca.key"
ca_csr: "{{ certificates_path }}/ca.csr"
ca_crt: "{{ certificates_path }}/ca.crt"

# Do not alter
force_overwrite: false

#Kubernetes components tls data
component_tls_subjects:
  kube-proxy:
    common_name: system:kube-proxy
    organization_name: system:node-proxier
  kube-controller-manager:
    common_name: system:kube-controller-manager
    organization_name: system:kube-controller-manager
  kube-scheduler:
    common_name: system:kube-scheduler
    organization_name: system:kube-scheduler


other:
  kube-apiserver:
    common_name: kubernetes
    organization_name: Kubernetes
    subject_alt_name: 
      - "IP:{{ node_ip }}"
      - "DNS:{{ node_hostname }}"
      - "DNS:{{ node_fqdn }}"
      - "DNS:kubernetes.default"
      - "DNS:kubernetes.default.svc"
      - "DNS:kubernetes.default.svc.cluster"
      - "DNS:kubernetes.svc.cluster.local"