---
# Installs Container Runtime Interface CLI
- name: Download CRI binary
  ansible.builtin.get_url:
    url: "{{ cri_release_url }}"
    dest: "{{ cri_tarball }}"
    mode: "0655"

- name: Extract and install CRI binary
  ansible.builtin.unarchive:
    src: "{{ cri_tarball }}"
    dest: "{{ cri_bin_dir }}"
    mode: "0555"
    remote_src: true
