---
# Creates -and signs- certificate key-pairs for the admin.
- name: "Generate the admin private key"
  openssl_privatekey:
    path: "{{ certificates_path }}/admin.key"
    force: "{{ force_overwrite }}"
  register: admin_key

- name: "Generate a CSR for the admin private key"
  openssl_csr:
    path: "{{ certificates_path }}/admin.csr"
    privatekey_path: "{{ certificates_path }}/admin.key"
    common_name: admin
    organization_name: system:masters
    force: "{{ force_overwrite }}"
  
- name: "Create the public key for the admin and sign with CA"
  community.crypto.x509_certificate:
    path: "{{ certificates_path }}/admin.crt"
    csr_path: "{{ certificates_path }}/admin.csr"
    ownca_path: "{{ ca_crt }}"
    ownca_privatekey_path: "{{ ca_key }}"
    provider: ownca
    force: "{{ force_overwrite }}"
  register: admin_crt

- name: "Debug public key"
  debug: 
    var: admin_crt.diff.after.public_key


    #Complete!