---
# Creates -and signs- certificates and generates kubeconfig for K8s componentes.
- name: "Generate the {{ tls_subject_name }} private key"
  openssl_privatekey:
    path: "{{ certificates_path }}/{{ tls_subject_name }}.key"
    force: "{{ force_overwrite }}"

- name: "Generate a CSR for the {{ tls_subject_name }} private key"
  openssl_csr:
    path: "{{ certificates_path }}/{{ tls_subject_name }}.csr"
    privatekey_path: "{{ certificates_path }}/{{ tls_subject_name }}.key"
    common_name: "{{ tls_subject_common_name }}"
    organization_name: "{{ tls_subject_organization_name }}"
    force: "{{ force_overwrite }}"
  when: subject_alt_name is not defined

- name: "Generate a CSR for the {{ tls_subject_name }} private key (with SAN)"
  openssl_csr:
    path: "{{ certificates_path }}/{{ tls_subject_name }}.csr"
    privatekey_path: "{{ certificates_path }}/{{ tls_subject_name }}.key"
    common_name: "{{ tls_subject_common_name }}"
    organization_name: "{{ tls_subject_organization_name }}"
    subject_alt_name: "{{ tls_subject_subject_alt_name }}"
    force: "{{ force_overwrite }}"
  when: subject_alt_name is defined
  
- name: "Create the public key for the {{ tls_subject_name }} and sign with CA"
  community.crypto.x509_certificate:
    path: "{{ certificates_path }}/{{ tls_subject_name }}.crt"
    csr_path: "{{ certificates_path }}/{{ tls_subject_name }}.csr"
    ownca_path: "{{ ca_crt }}"
    ownca_privatekey_path: "{{ ca_key }}"
    provider: ownca
    force: "{{ force_overwrite }}"

- name: "Register info on the public key for {{ tls_subject_name }} component"
  community.crypto.x509_certificate_info:
    path: "{{ certificates_path }}/{{ tls_subject_name }}.crt"
  register: tls_subject_crt

- name: "Store the component key content encoded in base64 (no output)"
  ansible.builtin.set_fact:
    tls_subject_key_content:  "{{ lookup('ansible.builtin.file', certificates_path+'/'+tls_subject_name+'.key') | string | b64encode }}"

- name: "Store the component cert content encoded in base64"
  ansible.builtin.set_fact:
    tls_subject_crt_content:  "{{ tls_subject_crt.public_key | string | b64encode }}"

- name: Create the kubeconfig file for component
  ansible.builtin.template:
    src: roles/create_certificates/files/kubeconfig
    dest: "{{ kubeconfig_path }}/kubeconfig_{{ tls_subject_name }}"
    mode: '0444'
