---
- name: Generate the CA private key
  openssl_privatekey:
    path: "{{certificates_path}}/ca.key"
    force: "{{force_overwrite}}"
- name: Generate a CSR for the CA private key
  openssl_csr:
    path: "{{certificates_path}}/ca.csr"
    privatekey_path: "{{certificates_path}}/ca.key"
    common_name: KUBERNETES-CA
    force: "{{force_overwrite}}"
- name: Create the public key for the CA (self-signed)
  community.crypto.x509_certificate:
    path: "{{certificates_path}}/ca.crt"
    csr_path: "{{certificates_path}}/ca.csr"
    privatekey_path: "{{certificates_path}}/ca.key"
    provider: selfsigned
    force: "{{force_overwrite}}"
