---
# Tasks to run
- name: Create Certificates directory
  ansible.builtin.file:
    path: "{{ certificates_path }}"
    state: directory
    mode: "0664"
- name: Create Kubeconfig directory
  ansible.builtin.file:
    path: "{{ kubeconfig_path }}"
    state: directory
    mode: "0664"

- name: Create CA certificates (self-signed)
  ansible.builtin.include_tasks: certs_ca_k8s.yml

- name: Create certificates for components
  ansible.builtin.include_tasks: certs_generic.yml
  vars:
    tls_subject_name: "{{ item.key }}"
    tls_subject_common_name: "{{ item.value.common_name }}"
    tls_subject_organization_name: "{{ item.value.organization_name }}"
  loop: "{{ lookup('ansible.builtin.dict',component_tls_subjects) }}"

- name: Create certificates for Kubelets
  ansible.builtin.include_tasks: certs_generic.yml
  vars:
    tls_subject_name: "{{ item.key }}"
    tls_subject_common_name: "{{ kubelet_tls_subject.common_name }}:{{ item.key }}"
    tls_subject_organization_name: "{{ kubelet_tls_subject.organization_name }}"
    tls_subject_subject_alt_name:
      - "IP:{{ item.value.ip }}"
      - "DNS:{{ item.key }}"
      - "DNS:{{ item.value.fqdn }}"
  loop: "{{ lookup('ansible.builtin.dict', nodes_worker)}}"

# TEMPORARY! This needs refactor to make it so that issues one key-pair for Kube-APIserver, but with all master IPs and hostnames.
- name: Create certificates for Kube-API-servers
  ansible.builtin.include_tasks: certs_generic.yml
  vars:
    tls_subject_name: "{{ item.key }}"
    tls_subject_common_name: "{{ kube_apiserver_tls_subject.common_name }}"
    tls_subject_organization_name: "{{ kube_apiserver_tls_subject.organization_name }}"
    tls_subject_subject_alt_name:
      - "IP:{{ item.value.ip }}"
      - "DNS:{{ item.key }}"
      - "DNS:{{ item.value.fqdn }}"
      - "DNS:kubernetes.default"
      - "DNS:kubernetes.default.svc"
      - "DNS:kubernetes.default.svc.cluster"
      - "DNS:kubernetes.svc.cluster.local"
  loop: "{{ lookup('ansible.builtin.dict', nodes_master)}}"
