- name: Download Containerd binary
  ansible.builtin.get_url:
    url: https://github.com/containerd/containerd/releases/download/v{{containerd_version}}/containerd-{{containerd_version}}-linux-{{architecture}}.tar.gz
    dest: "{{ containerd_tarball }}"
    mode: 0655
- name: Extract Containerd binary
  ansible.builtin.unarchive:
    src: "{{ containerd_tarball }}"
    dest: "{{ containerd_dir }}"
    mode: 0555
    remote_src: true
- name: Copy Containerd Systemd Unit File
  ansible.builtin.copy:
    src: files/containerd.service
    dest: "{{ containerd_systemd_unit }}"
    mode: 0444    
- name: Enable Containerd Systemd service
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    state: started
    name: containerd.service
- name: Start Containerd Systemd service
  ansible.builtin.systemd:
    state: started
    name: containerd    
